name: timely
description: Task manager & To-Do list app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: ">=2.11.0 <3.0.0"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"

dependencies:
  flutter:
    sdk: flutter
  flutter_appavailability:
    git:
      url: https://github.com/bwhiteTP/flutter_appavailability.git
      ref: 26461d5296cd8c0a58da1d9c5f1e960643ebb323
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.3
  firebase_app_check: ^0.0.1+3
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  flutter_local_notifications: ^6.0.0
  flutter_svg: ^0.22.0
  image_picker: ^0.8.2
  intl: ^0.17.0
  stacked: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd/CircularStd-Bold.otf
          weight: 800
        - asset: assets/fonts/CircularStd/CircularStd-Medium.otf
          weight: 700
        - asset: assets/fonts/CircularStd/CircularStd-Book.otf
          weight: 400
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/Muli/Muli-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Muli/Muli.ttf
          weight: 400
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
